# Generated by Django 4.2.10 on 2026-06-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='service_areas',
            field=models.ManyToManyField(related_name='providers', to='services.servicearea'),
        ),
    ]
