# Generated by Django 4.2.10 on 2026-06-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_provider_service_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
