services:
  - type: web
    name: homefix-app
    env: python
    plan: free
    rootDir: homeservices
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: homefix-app.onrender.com
